# Generated by Django 3.2.9 on 2022-05-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(blank=True, max_length=12000000, null=True, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
