# Generated by Django 3.2.9 on 2022-05-06 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0002_auto_20220412_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('default_permission', models.BooleanField(choices=[(True, 'allow'), (False, 'deny')])),
                ('owner_applicability', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionsToPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.BooleanField(choices=[(True, 'allow'), (False, 'deny')])),
                ('by_owner_only', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_auth.action')),
            ],
        ),
        migrations.CreateModel(
            name='KeyChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('actions', models.ManyToManyField(related_name='permit', through='rest_auth.ActionsToPermit', to='rest_auth.Action')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='rest_auth.securityzone')),
                ('permits', models.ManyToManyField(blank=True, related_name='zones', to='rest_auth.Permit')),
                ('security_keychain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_auth.keychain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='roles', to='rest_auth.Group')),
                ('permits', models.ManyToManyField(blank=True, related_name='roles', to='rest_auth.Permit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='permit',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='rest_auth.plugin'),
        ),
        migrations.AddField(
            model_name='keychain',
            name='permits',
            field=models.ManyToManyField(blank=True, related_name='keychains', to='rest_auth.Permit'),
        ),
        migrations.AddField(
            model_name='keychain',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keychains', to='rest_auth.securityzone'),
        ),
        migrations.AddField(
            model_name='actionstopermit',
            name='permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_auth.permit'),
        ),
        migrations.AddField(
            model_name='action',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rest_auth.plugin'),
        ),
    ]
