# Generated by Django 3.2.9 on 2023-10-19 23:50

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0003_auto_20220627_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCoveredClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('class_import_str', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermitKeychain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keychain_id', models.CharField(max_length=256)),
                ('auth_covered_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_keychain', to='rest_auth.authcoveredclass')),
            ],
        ),
        migrations.RemoveField(
            model_name='protectedresource',
            name='keychain',
        ),
        migrations.RemoveField(
            model_name='protectedresource',
            name='owner',
        ),
        migrations.CreateModel(
            name='KeycloakUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest_auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='owner_applicability',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='plugin',
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='rest_auth.action'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='rest_auth.permit'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='actions',
            field=models.ManyToManyField(related_name='permits', through='rest_auth.AccessRule', to='rest_auth.Action'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='rest_auth.Group', verbose_name='groups'),
        ),
        migrations.DeleteModel(
            name='KeyChain',
        ),
        migrations.DeleteModel(
            name='ProtectedResource',
        ),
        migrations.AddField(
            model_name='permitkeychain',
            name='permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_keychain', to='rest_auth.permit'),
        ),
        migrations.AddField(
            model_name='authcoveredclass',
            name='actions',
            field=models.ManyToManyField(related_name='auth_covered_classes', to='rest_auth.Action'),
        ),
        migrations.AddField(
            model_name='authcoveredclass',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_covered_classes', to='rest_auth.plugin'),
        ),
    ]
