# Generated by Django 3.2.9 on 2023-09-19 16:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0005_remove_action_owner_applicability'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest_auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='authcoveredclass',
            name='actions',
            field=models.ManyToManyField(related_name='auth_covered_classes', to='rest_auth.Action'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
