# Generated by Django 3.2.9 on 2023-10-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0006_auto_20230919_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcoveredclass',
            name='class_import_str',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
