version: "3.9"

services:
  postgres:
    image: postgres:12.9
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis

  zookeeper:
    image: 'bitnami/zookeeper:3.6.3'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.0.0'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  ldap:
    image: 'rroemhild/test-openldap'

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    user: ${CURRENT_UID}
    volumes:
      - ./:/complex_rest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8090
      - KC_FEATURES=account-api,account2,authorization,client-policies,impersonation,docker,scripts
    entrypoint: /complex_rest/docs/docker_dev/keycloak/entrypoint.sh
    command: /opt/keycloak/bin/kc.sh start-dev
    depends_on:
      - ldap

  celery-worker:
    build:
      context: ./
      dockerfile: ./docs/docker_dev/complex_rest/Dockerfile

    volumes:
      - ./:/complex_rest
    user: ${CURRENT_UID}

    depends_on:
      - postgres
      - redis
      - kafka
    command: "celery --app core.celeryapp:app worker --loglevel=INFO --concurrency 8"
    environment:
      - REST_CONF=/complex_rest/docs/docker_dev/complex_rest/rest_test.conf

  celery-beat:
    build:
      context: ./
      dockerfile: ./docs/docker_dev/complex_rest/Dockerfile

    volumes:
      - ./:/complex_rest
    user: ${CURRENT_UID}

    depends_on:
      - postgres
      - redis
      - kafka
    command: "celery --app core.celeryapp:app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    environment:
      - REST_CONF=/complex_rest/docs/docker_dev/complex_rest/rest_test.conf

  complex_rest:
    build:
      context: ./
      dockerfile: ./docs/docker_dev/complex_rest/Dockerfile
    image: "complex_rest:1.0.2"

    volumes:
      - ./:/complex_rest
    user: ${CURRENT_UID}
    command: "python /complex_rest/complex_rest/manage.py runserver [::]:8080"
    environment:
      - REST_CONF=/complex_rest/docs/docker_dev/complex_rest/rest_test.conf

    depends_on:
      - postgres
      - redis
      - kafka
      - keycloak
