try:
    from .local import *
except ModuleNotFoundError:
    try:
        # will be generated by make pack
        from .production import *
    except ModuleNotFoundError:
        from .dev import *