# Generated by Django 3.2.9 on 2023-05-11 09:43

from django.db import migrations, models
import rest_auth.models.abc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rolemodel_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginKeychainUUID',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('_zone', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(rest_auth.models.abc.IKeyChain, models.Model),
        ),
        migrations.CreateModel(
            name='SomePluginAuthCoveredModelUUID',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('_owner_id', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_keychain_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(rest_auth.models.abc.IAuthCovered, models.Model),
        ),
        migrations.RemoveField(
            model_name='pluginkeychain',
            name='_permits',
        ),
    ]
